### ISSUE TITLE
Several pix_opencv objects not found after compilation

### ISSUE THREAD

**Issue by hellocatfood** [avilleret/pix_opencv#4]
I compiled pix_opencv on Ubuntu 15.04 for pd-extended. I tried opening [pix_opencv_help] and I got a few errors about missing objects. In the pd console:

```
[pix_opencv_haarcascade]: ERROR: Could not load classifier cascade

[pix_opencv_knear]: pix_opencv_knear : loaded : 0 samples from 
[pix_opencv_knear]: can't load patterns
 pix_opencv_facetracker
... couldn't create
```

In the Linux terminal:

```
OpenCV Error: Bad argument (train data must be floating-point matrix) in cvCheckTrainData, file /home/hellocatfood/Desktop/opencv-2.4.10/modules/ml/src/inner_functions.cpp, line 857
```

**Comment by avilleret** [comment]
Which version have you build ?
Please note that you may have some information in the Pd's console about the feature available.

`[pix_opencv_haarcascade]` tries to load `./haarcascade_frontalface_alt.xml` by default and display an error if the file is not found.
`[pix_opencv_knear]` also tries to load some default file at loading and print an error when it fails.

Concerning  `pix_opencv_facetracker` you need to build the facetracker library to use it.
Please have a look to the git submodule.

I'll push some fix for the first problem (at least, the error will be more precise).

**Comment by avilleret** [comment]
fixed with https://github.com/avilleret/pix_opencv/commit/a94ae530202f6658ca3f3c80bb563e13dc93a8eb

**Comment by hellocatfood** [comment]
I've now built `a94ae53` and still getting errors with some of the objects.

I built the facetracker library and tested it so can confirm that it works. Where should the binary be placed so that it is picked up by the object?

**Comment by avilleret** [comment]
do you see this : https://github.com/avilleret/pix_opencv/wiki ?
(I'll put a link from the Readme.md)

you have to re-run ./configure after making the facetracker lib.
And you may need to `make clean` then `make all` to build `pix_opencv_facetracker`.

If you want to use `pix_opencv_surf` you need the OpenCV non-free module.
It's not available from the Ubuntu repository, so you have to build OpenCV from source (and enable non-free feature building) to get this one to work.

**Comment by hellocatfood** [comment]
I think I now have built `pix_opencv_facetracker`, thank you. However, when I try to run the help patch it crashes pd. This is the error I get:

````
pd-extended: src/lib/Tracker.cc:59: void FACETRACKER::Tracker::Load(const char*): Assertion `s.is_open()' failed.
Pd: signal 6
````

**Comment by avilleret** [comment]
hi,

this is another issue,
please open a new one

btw here is a workaround : copy (or symlink) the model folder in the folder
of the patch that uses pix_opencv_facetracker
for instance, if you're loading the help file from the repo folder, copy
the model folder into the help folder

if you do a make install, the help files will be at the same level of the
model folder and it should work

+
a



--
do it yourself
http://antoine.villeret.free.fr

2015-05-29 1:12 GMT+02:00 Antonio <notifications@github.com>:

**Comment by hellocatfood** [comment]
Thanks, this all worked thanks to your instructions
